In [2]:
#Numpy - Array Manipulation.

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,10 , (3,4))

In [5]:
arr

array([[3, 3, 1, 9],
       [9, 1, 5, 5],
       [2, 7, 9, 4]])

In [11]:
arr.reshape(4,3)

array([[3, 3, 1],
       [9, 9, 1],
       [5, 5, 2],
       [7, 9, 4]])

In [12]:
arr.reshape(6,2)

array([[3, 3],
       [1, 9],
       [9, 1],
       [5, 5],
       [2, 7],
       [9, 4]])

In [13]:
arr.reshape(2,6)

array([[3, 3, 1, 9, 9, 1],
       [5, 5, 2, 7, 9, 4]])

In [14]:
arr.reshape(2,-242342)

array([[3, 3, 1, 9, 9, 1],
       [5, 5, 2, 7, 9, 4]])

In [15]:
arr.T

array([[3, 9, 2],
       [3, 1, 7],
       [1, 5, 9],
       [9, 5, 4]])

In [16]:
arr

array([[3, 3, 1, 9],
       [9, 1, 5, 5],
       [2, 7, 9, 4]])

In [17]:
arr.flatten()

array([3, 3, 1, 9, 9, 1, 5, 5, 2, 7, 9, 4])

In [18]:
arr1 = np.array([1,2,3,3,4])

In [19]:
arr1.ndim

1

In [20]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [21]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [22]:
arr

array([[3, 3, 1, 9],
       [9, 1, 5, 5],
       [2, 7, 9, 4]])

In [23]:
np.squeeze(arr)

array([[3, 3, 1, 9],
       [9, 1, 5, 5],
       [2, 7, 9, 4]])

In [24]:
data = np.array([[1] , [2] , [3]])

In [25]:
data

array([[1],
       [2],
       [3]])

In [26]:
np.squeeze(data)

array([1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 3, 4])

In [28]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [29]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [30]:
arr1

array([1, 2, 3, 3, 4])

In [31]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [32]:
#Numpy - Binary Operators.

In [33]:
arr1 = np.random.randint(1,10 , (3,4))

In [34]:
arr2 = np.random.randint(1,10 , (3,4))

In [35]:
arr1

array([[4, 4, 8, 4],
       [9, 5, 8, 6],
       [2, 4, 8, 1]])

In [36]:
arr2

array([[6, 8, 3, 3],
       [6, 6, 5, 5],
       [7, 1, 9, 8]])

In [37]:
arr1+arr2

array([[10, 12, 11,  7],
       [15, 11, 13, 11],
       [ 9,  5, 17,  9]])

In [38]:
arr1*arr2

array([[24, 32, 24, 12],
       [54, 30, 40, 30],
       [14,  4, 72,  8]])

In [39]:
arr1/arr2

array([[0.66666667, 0.5       , 2.66666667, 1.33333333],
       [1.5       , 0.83333333, 1.6       , 1.2       ],
       [0.28571429, 4.        , 0.88888889, 0.125     ]])

In [40]:
arr1-arr2

array([[-2, -4,  5,  1],
       [ 3, -1,  3,  1],
       [-5,  3, -1, -7]])

In [41]:
arr1%arr2

array([[4, 4, 2, 1],
       [3, 5, 3, 1],
       [2, 0, 8, 1]])

In [42]:
arr1 ** arr2

array([[     4096,     65536,       512,        64],
       [   531441,     15625,     32768,      7776],
       [      128,         4, 134217728,         1]])

In [43]:
arr1 & arr2

array([[4, 0, 0, 0],
       [0, 4, 0, 4],
       [2, 0, 8, 0]])

In [44]:
arr1

array([[4, 4, 8, 4],
       [9, 5, 8, 6],
       [2, 4, 8, 1]])

In [45]:
arr2

array([[6, 8, 3, 3],
       [6, 6, 5, 5],
       [7, 1, 9, 8]])

In [46]:
~arr1

array([[ -5,  -5,  -9,  -5],
       [-10,  -6,  -9,  -7],
       [ -3,  -5,  -9,  -2]])

In [47]:
arr1|arr2

array([[ 6, 12, 11,  7],
       [15,  7, 13,  7],
       [ 7,  5,  9,  9]])

In [48]:
arr1>arr2

array([[False, False,  True,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

In [49]:
#Numpy - String Functions.

In [50]:
arr = np.array(['sudh' , "Kumar"])

In [51]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [52]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [53]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [54]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [55]:
#Numpy - Mathematical Functions.

In [56]:
arr1

array([[4, 4, 8, 4],
       [9, 5, 8, 6],
       [2, 4, 8, 1]])

In [57]:
np.sin(arr1)

array([[-0.7568025 , -0.7568025 ,  0.98935825, -0.7568025 ],
       [ 0.41211849, -0.95892427,  0.98935825, -0.2794155 ],
       [ 0.90929743, -0.7568025 ,  0.98935825,  0.84147098]])

In [58]:
np.cos(arr1)

array([[-0.65364362, -0.65364362, -0.14550003, -0.65364362],
       [-0.91113026,  0.28366219, -0.14550003,  0.96017029],
       [-0.41614684, -0.65364362, -0.14550003,  0.54030231]])

In [59]:
np.tan(arr1)

array([[ 1.15782128,  1.15782128, -6.79971146,  1.15782128],
       [-0.45231566, -3.38051501, -6.79971146, -0.29100619],
       [-2.18503986,  1.15782128, -6.79971146,  1.55740772]])

In [60]:
np.tanh(arr1)

array([[0.9993293 , 0.9993293 , 0.99999977, 0.9993293 ],
       [0.99999997, 0.9999092 , 0.99999977, 0.99998771],
       [0.96402758, 0.9993293 , 0.99999977, 0.76159416]])

In [61]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.90308999, 0.60205999],
       [0.95424251, 0.69897   , 0.90308999, 0.77815125],
       [0.30103   , 0.60205999, 0.90308999, 0.        ]])

In [62]:
np.exp(arr1)

array([[5.45981500e+01, 5.45981500e+01, 2.98095799e+03, 5.45981500e+01],
       [8.10308393e+03, 1.48413159e+02, 2.98095799e+03, 4.03428793e+02],
       [7.38905610e+00, 5.45981500e+01, 2.98095799e+03, 2.71828183e+00]])

In [63]:
np.sqrt(arr1)

array([[2.        , 2.        , 2.82842712, 2.        ],
       [3.        , 2.23606798, 2.82842712, 2.44948974],
       [1.41421356, 2.        , 2.82842712, 1.        ]])

In [64]:
np.power(arr1,2)

array([[16, 16, 64, 16],
       [81, 25, 64, 36],
       [ 4, 16, 64,  1]], dtype=int32)

In [65]:
np.mean(arr1)

5.25

In [66]:
np.median(arr1)

4.5

In [67]:
np.std(arr1)

2.4537386440559095

In [68]:
np.var(arr1)

6.020833333333333

In [69]:
np.min(arr1
      )

1

In [70]:
np.max(arr1)

9